import type { Tool } from "../types";

export const tools: Tool[] = [
  {
    id: 'coindar',
    name: 'The coin perspective third line',
    description: 'Live crypto calendar to discover launches and protocol updates.',
    category: 'Analytics',
    tags: ['recent', 'trending'],
    clicks: 1840,
    views: 24500,
    createdAt: '2025-01-14T10:00:00Z',
    logo: 'https://placehold.co/64x64?text=C',
    links: [
      { label: 'Telegram', url: '#' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'coin360',
    name: 'Coin360',
    description: 'Market heatmap for tracking price action at a glance.',
    category: 'Market',
    tags: ['popular'],
    clicks: 2120,
    views: 30250,
    createdAt: '2024-12-21T15:30:00Z',
    logo: 'https://placehold.co/64x64?text=C3',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'cryptoPanic',
    name: 'CryptoPanic',
    description: 'News aggregator for traders to monitor narratives.',
    category: 'News',
    tags: ['trending', 'popular'],
    clicks: 2750,
    views: 35120,
    createdAt: '2025-01-10T09:20:00Z',
    logo: 'https://placehold.co/64x64?text=CP',
    links: [
      { label: 'Telegram', url: '#' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'cryptoMiso',
    name: 'CryptoMiso',
    description: 'Ranks crypto projects by GitHub activity.',
    category: 'Developer',
    tags: ['recent'],
    clicks: 970,
    views: 8700,
    createdAt: '2025-01-18T19:45:00Z',
    logo: 'https://placehold.co/64x64?text=CM',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'coinPerspective',
    name: 'The Coin Perspective',
    description: 'Compare market caps to estimate upside scenarios.',
    category: 'Valuation',
    tags: ['popular'],
    clicks: 1980,
    views: 21000,
    createdAt: '2024-11-30T13:05:00Z',
    logo: 'https://placehold.co/64x64?text=TCP',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'dexGuru',
    name: 'DexGuru',
    description: 'Advanced DEX charts and wallet tracking.',
    category: 'Trading',
    tags: ['recent', 'popular'],
    clicks: 2350,
    views: 32950,
    createdAt: '2025-01-16T08:10:00Z',
    logo: 'https://placehold.co/64x64?text=DG',
    links: [
      { label: 'Telegram', url: '#' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'defiLlama',
    name: 'DefiLlama',
    description: 'TVL dashboard for DeFi protocols across chains.',
    category: 'Analytics',
    tags: ['trending'],
    clicks: 2600,
    views: 43000,
    createdAt: '2024-10-11T11:11:00Z',
    logo: 'https://placehold.co/64x64?text=DL',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'tokenTerminal',
    name: 'Token Terminal',
    description: 'Fundamental metrics for crypto projects.',
    category: 'Analytics',
    tags: ['popular', 'recent'],
    clicks: 1890,
    views: 28000,
    createdAt: '2025-01-12T17:25:00Z',
    logo: 'https://placehold.co/64x64?text=TT',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'nansen',
    name: 'Nansen',
    description: 'On-chain analytics platform for smart money tracking.',
    category: 'Analytics',
    tags: ['trending', 'popular'],
    clicks: 3200,
    views: 51200,
    createdAt: '2024-09-15T14:20:00Z',
    logo: 'https://placehold.co/64x64?text=N',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'metamask',
    name: 'MetaMask',
    description: 'Browser extension wallet for Ethereum and EVM chains.',
    category: 'Wallet',
    tags: ['popular'],
    clicks: 15200,
    views: 189000,
    createdAt: '2024-08-05T10:00:00Z',
    logo: 'https://placehold.co/64x64?text=MM',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'opensea',
    name: 'OpenSea',
    description: 'Largest NFT marketplace for buying and selling digital collectibles.',
    category: 'NFT',
    tags: ['popular', 'trending'],
    clicks: 8900,
    views: 125000,
    createdAt: '2024-07-22T16:45:00Z',
    logo: 'https://placehold.co/64x64?text=OS',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'etherscan',
    name: 'Etherscan',
    description: 'Blockchain explorer for Ethereum network transactions.',
    category: 'Explorer',
    tags: ['popular'],
    clicks: 11200,
    views: 156000,
    createdAt: '2024-06-10T09:30:00Z',
    logo: 'https://placehold.co/64x64?text=ES',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    description: 'Decentralized exchange protocol for token swaps.',
    category: 'Trading',
    tags: ['trending', 'popular'],
    clicks: 14500,
    views: 198000,
    createdAt: '2024-05-18T11:15:00Z',
    logo: 'https://placehold.co/64x64?text=UNI',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'certik',
    name: 'CertiK',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    category: 'Security',
    tags: ['recent', 'trending'],
    clicks: 2100,
    views: 28900,
    createdAt: '2025-01-20T13:50:00Z',
    logo: 'https://placehold.co/64x64?text=CK',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '#' },
      { label: 'Website', url: '#' },
    ],
  },
  {
    id: 'glassnode',
    name: 'Glassnode',
    description: 'On-chain metrics and intelligence for Bitcoin and Ethereum.',
    category: 'Analytics',
    tags: ['popular'],
    clicks: 3400,
    views: 47800,
    createdAt: '2024-12-05T08:25:00Z',
    logo: 'https://placehold.co/64x64?text=GN',
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: '#' },
    ],
  },
];