import type { Tool } from "../types";

export const tools: Tool[] = [
  {
    _id: 'coindar',
    name: 'The coin perspective third line',
    shortDescription: 'Live crypto calendar to discover launches and protocol updates.',
    fullDetail: 'A comprehensive cryptocurrency calendar that helps you stay updated with upcoming token launches, protocol updates, and important events in the crypto space. Track ICOs, airdrops, and major announcements.',
    category: 'Data Analytics',
    tags: ['Free', 'Web-based', 'No Signup'],
    clicks: 1840,
    views: 24500,
    createdAt: '2025-01-14T10:00:00Z',
    bookmarks: 125,
    logo: 'https://placehold.co/64x64?text=C',
    toolImages: ['https://placehold.co/800x400?text=Crypto+Calendar'],
    links: [
      { label: 'Telegram', url: 'https://t.me/coindar' },
      { label: 'X', url: 'https://twitter.com/coindar' },
      { label: 'Website', url: 'https://coindar.org' },
    ],
  },
  {
    _id: 'coin360',
    name: 'Coin360',
    shortDescription: 'Market heatmap for tracking price action at a glance.',
    fullDetail: 'Interactive cryptocurrency market heatmap that visualizes price movements across different coins. Get a quick overview of the market sentiment and identify trending assets.',
    category: 'Data Analytics',
    tags: ['Free', 'Web-based', 'Cloud'],
    clicks: 2120,
    views: 30250,
    createdAt: '2024-12-21T15:30:00Z',
    bookmarks: 180,
    logo: 'https://placehold.co/64x64?text=C3',
    toolImages: ['https://placehold.co/800x400?text=Coin360+Heatmap'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/coin360' },
      { label: 'Website', url: 'https://coin360.com' },
    ],
  },
  {
    _id: 'cryptoPanic',
    name: 'CryptoPanic',
    shortDescription: 'News aggregator for traders to monitor narratives.',
    fullDetail: 'Real-time cryptocurrency news aggregator that collects news from various sources. Monitor market sentiment, breaking news, and social media discussions all in one place.',
    category: 'Other',
    tags: ['Free', 'Web-based', 'API'],
    clicks: 2750,
    views: 35120,
    createdAt: '2025-01-10T09:20:00Z',
    bookmarks: 210,
    logo: 'https://placehold.co/64x64?text=CP',
    toolImages: ['https://placehold.co/800x400?text=CryptoPanic+News'],
    links: [
      { label: 'Telegram', url: 'https://t.me/cryptopanic' },
      { label: 'X', url: 'https://twitter.com/cryptopanic' },
      { label: 'Website', url: 'https://cryptopanic.com' },
    ],
  },
  {
    _id: 'cryptoMiso',
    name: 'CryptoMiso',
    shortDescription: 'Ranks crypto projects by GitHub activity.',
    fullDetail: 'GitHub activity tracker for cryptocurrency projects. See which projects are actively being developed by monitoring commits, pull requests, and developer activity.',
    category: 'Development',
    tags: ['Free', 'Web-based', 'Open Source'],
    clicks: 970,
    views: 8700,
    createdAt: '2025-01-18T19:45:00Z',
    bookmarks: 45,
    logo: 'https://placehold.co/64x64?text=CM',
    toolImages: ['https://placehold.co/800x400?text=CryptoMiso'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://cryptomiso.com' },
    ],
  },
  {
    _id: 'coinPerspective',
    name: 'The Coin Perspective',
    shortDescription: 'Compare market caps to estimate upside scenarios.',
    fullDetail: 'Market cap comparison tool that helps you understand potential growth scenarios. Compare current market caps to historical data and estimate future valuations.',
    category: 'Data Analytics',
    tags: ['Free', 'Web-based'],
    clicks: 1980,
    views: 21000,
    createdAt: '2024-11-30T13:05:00Z',
    bookmarks: 95,
    logo: 'https://placehold.co/64x64?text=TCP',
    toolImages: ['https://placehold.co/800x400?text=Coin+Perspective'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://coinperspective.com' },
    ],
  },
  {
    _id: 'dexGuru',
    name: 'DexGuru',
    shortDescription: 'Advanced DEX charts and wallet tracking.',
    fullDetail: 'Professional-grade decentralized exchange analytics platform. Track token prices, liquidity, trading volume, and wallet activity across multiple DEXes.',
    category: 'Other',
    tags: ['Free', 'Web-based', 'Cloud'],
    clicks: 2350,
    views: 32950,
    createdAt: '2025-01-16T08:10:00Z',
    bookmarks: 165,
    logo: 'https://placehold.co/64x64?text=DG',
    toolImages: ['https://placehold.co/800x400?text=DexGuru'],
    links: [
      { label: 'Telegram', url: 'https://t.me/dexguru' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://dexguru.com' },
    ],
  },
  {
    _id: 'defiLlama',
    name: 'DefiLlama',
    shortDescription: 'TVL dashboard for DeFi protocols across chains.',
    fullDetail: 'Comprehensive DeFi analytics platform tracking Total Value Locked (TVL) across hundreds of protocols and multiple blockchains. Monitor yield farming, lending, and liquidity pools.',
    category: 'Data Analytics',
    tags: ['Free', 'Web-based', 'Open Source'],
    clicks: 2600,
    views: 43000,
    createdAt: '2024-10-11T11:11:00Z',
    bookmarks: 320,
    logo: 'https://placehold.co/64x64?text=DL',
    toolImages: ['https://placehold.co/800x400?text=DefiLlama'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/defillama' },
      { label: 'Website', url: 'https://defillama.com' },
    ],
  },
  {
    _id: 'tokenTerminal',
    name: 'Token Terminal',
    shortDescription: 'Fundamental metrics for crypto projects.',
    fullDetail: 'Financial metrics and analytics for crypto protocols. Analyze revenue, profit margins, and other fundamental data to make informed investment decisions.',
    category: 'Data Analytics',
    tags: ['Free', 'Web-based', 'Paid'],
    clicks: 1890,
    views: 28000,
    createdAt: '2025-01-12T17:25:00Z',
    bookmarks: 140,
    logo: 'https://placehold.co/64x64?text=TT',
    toolImages: ['https://placehold.co/800x400?text=Token+Terminal'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://tokenterminal.com' },
    ],
  },
  {
    _id: 'nansen',
    name: 'Nansen',
    shortDescription: 'On-chain analytics platform for smart money tracking.',
    fullDetail: 'Premium on-chain analytics platform that tracks smart money wallets. Follow whale movements, identify profitable strategies, and get early signals on market trends.',
    category: 'Data Analytics',
    tags: ['Paid', 'Web-based', 'Cloud'],
    clicks: 3200,
    views: 51200,
    createdAt: '2024-09-15T14:20:00Z',
    bookmarks: 450,
    logo: 'https://placehold.co/64x64?text=N',
    toolImages: ['https://placehold.co/800x400?text=Nansen'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/nansen_ai' },
      { label: 'Website', url: 'https://nansen.ai' },
    ],
  },
  {
    _id: 'metamask',
    name: 'MetaMask',
    shortDescription: 'Browser extension wallet for Ethereum and EVM chains.',
    fullDetail: 'The most popular Ethereum and EVM-compatible blockchain wallet. Store, send, and receive cryptocurrencies, interact with DApps, and manage your digital assets securely.',
    category: 'Other',
    tags: ['Free', 'Web-based', 'Plugin'],
    clicks: 15200,
    views: 189000,
    createdAt: '2024-08-05T10:00:00Z',
    bookmarks: 2800,
    logo: 'https://placehold.co/64x64?text=MM',
    toolImages: ['https://placehold.co/800x400?text=MetaMask'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/metamask' },
      { label: 'Website', url: 'https://metamask.io' },
    ],
  },
  {
    _id: 'opensea',
    name: 'OpenSea',
    shortDescription: 'Largest NFT marketplace for buying and selling digital collectibles.',
    fullDetail: 'The world\'s largest NFT marketplace. Buy, sell, and discover rare digital items and collectibles. Trade NFTs from top collections and create your own.',
    category: 'E-commerce',
    tags: ['Free', 'Web-based', 'Cloud'],
    clicks: 8900,
    views: 125000,
    createdAt: '2024-07-22T16:45:00Z',
    bookmarks: 1520,
    logo: 'https://placehold.co/64x64?text=OS',
    toolImages: ['https://placehold.co/800x400?text=OpenSea'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/opensea' },
      { label: 'Website', url: 'https://opensea.io' },
    ],
  },
  {
    _id: 'etherscan',
    name: 'Etherscan',
    shortDescription: 'Blockchain explorer for Ethereum network transactions.',
    fullDetail: 'Ethereum blockchain explorer and analytics platform. Search transactions, addresses, tokens, and smart contracts. Verify contract code and interact with deployed contracts.',
    category: 'Development',
    tags: ['Free', 'Web-based'],
    clicks: 11200,
    views: 156000,
    createdAt: '2024-06-10T09:30:00Z',
    bookmarks: 2100,
    logo: 'https://placehold.co/64x64?text=ES',
    toolImages: ['https://placehold.co/800x400?text=Etherscan'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://etherscan.io' },
    ],
  },
  {
    _id: 'uniswap',
    name: 'Uniswap',
    shortDescription: 'Decentralized exchange protocol for token swaps.',
    fullDetail: 'Leading decentralized exchange protocol built on Ethereum. Swap tokens, provide liquidity, and earn fees. No intermediaries, no centralized order books.',
    category: 'Other',
    tags: ['Free', 'Web-based', 'Open Source'],
    clicks: 14500,
    views: 198000,
    createdAt: '2024-05-18T11:15:00Z',
    bookmarks: 3400,
    logo: 'https://placehold.co/64x64?text=UNI',
    toolImages: ['https://placehold.co/800x400?text=Uniswap'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/uniswap' },
      { label: 'Website', url: 'https://uniswap.org' },
    ],
  },
  {
    _id: 'certik',
    name: 'CertiK',
    shortDescription: 'Blockchain security platform for smart contract audits.',
    fullDetail: 'Leading blockchain security firm specializing in smart contract audits, penetration testing, and formal verification. Secure your DeFi protocols and smart contracts.',
    category: 'Other',
    tags: ['Paid', 'Web-based', 'Cloud'],
    clicks: 2100,
    views: 28900,
    createdAt: '2025-01-20T13:50:00Z',
    bookmarks: 88,
    logo: 'https://placehold.co/64x64?text=CK',
    toolImages: ['https://placehold.co/800x400?text=CertiK'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: 'https://twitter.com/certikorg' },
      { label: 'Website', url: 'https://certik.com' },
    ],
  },
  {
    _id: 'glassnode',
    name: 'Glassnode',
    shortDescription: 'On-chain metrics and intelligence for Bitcoin and Ethereum.',
    fullDetail: 'Professional-grade on-chain analytics platform providing insights into Bitcoin and Ethereum networks. Track network health, market cycles, and on-chain indicators.',
    category: 'Data Analytics',
    tags: ['Free', 'Paid', 'Web-based', 'Cloud'],
    clicks: 3400,
    views: 47800,
    createdAt: '2024-12-05T08:25:00Z',
    bookmarks: 275,
    logo: 'https://placehold.co/64x64?text=GN',
    toolImages: ['https://placehold.co/800x400?text=Glassnode'],
    links: [
      { label: 'Telegram', url: '' },
      { label: 'X', url: '' },
      { label: 'Website', url: 'https://glassnode.com' },
    ],
  },
];
