export { default as ToolViewPage } from './ToolView';
export { default as HomePage } from './Home';
export { default as ContactPage } from './Contact';
export { default as PopularPage } from './Popular';
export { default as TrendingPage } from './Trending';
export { default as DashboardPage } from './Dashboard';
export { default as SubmitToolPage } from './SubmitTool';
export { default as NotFoundPage } from './NotFoundPage';
export { default as CategoriesPage } from './Categories';